## Test 3.0


In [1]:
number = 10

if number%2==0:
    print('Number is even')
else:
    print('Number is odd')

Number is even


In [2]:
for x in range(10,0,-1):
    print(x)

10
9
8
7
6
5
4
3
2
1


In [3]:
while(True):
    val = int(input())
    if val == 0:
        print('Exiting the while loop')
        break
    else:
        print(f'Entered: {val}')

Entered: 4
Entered: 7
Exiting the while loop


In [4]:
def add(a,b):
    return a+b

add(10,30)

40

In [5]:
[1,4,9]

[1, 4, 9]

In [6]:
def is_even(a):
    if a%2==0:
        return a

list(filter(is_even,[5,6,8,123,54,67]))

[6, 8, 54]

Explain the purpose of the else block in a try-except-else construct.

In [7]:
'''Else block is executed when the try block is completely 
executed without any error/exception'''

'Else block is executed when the try block is completely \nexecuted without any error/exception'

In [8]:
def divide(a,b):
    try:
        c = a/b
        return c
    except ZeroDivisionError:
        print('Cannot Divide by zero')

divide(10,0)

Cannot Divide by zero


In [9]:
# Output of this lambda function is 8, because this adds the two values

In [10]:
class Dog:
    def __init__(self,name,breed):
        self.name = name
        self.breed = breed
    
    def bark(self):
        print('Bhaw...Bhaw...')

In [11]:
dog_a = Dog('Tommy','German-shephard')
dog_b = Dog('Jerry','Labrador')

dog_a.bark()
dog_b.bark()

Bhaw...Bhaw...
Bhaw...Bhaw...


In [12]:
# Class variables are usable throughout the class of the program,they are defined in the '__init__' constructor
# while instance variables are limited to function or conditional-statements, and cannot be used outside it

In [13]:
"apple"

'apple'

In [14]:
def square(a:list):
    return [x**2 for x in a]
a = [2,3,4,5,6]
square(a)

[4, 9, 16, 25, 36]

In [15]:
# map() returns the all list of values with applied operations
# filter() returns the list of values which satisfies the given condition

In [16]:
import numpy as np

### Numpy

In [17]:
mat = np.random.randint(0,10,(3,3))
mat

array([[9, 2, 2],
       [6, 9, 6],
       [3, 6, 6]], dtype=int32)

In [18]:
mat[:2]

array([[9, 2, 2],
       [6, 9, 6]], dtype=int32)

Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.

In [19]:
mat_a = np.random.randint(0,10,(3,3))
mat_b = np.random.randint(0,10,(3,3))

print('Along axis = 0 : \n',np.concatenate((mat_a,mat_b)))
print('\nAlong axis = 1 : \n',np.concatenate((mat_a,mat_b),axis=1))

Along axis = 0 : 
 [[1 0 3]
 [6 2 1]
 [6 8 0]
 [7 7 7]
 [4 8 7]
 [5 1 6]]

Along axis = 1 : 
 [[1 0 3 7 7 7]
 [6 2 1 4 8 7]
 [6 8 0 5 1 6]]


In [20]:
print('Addition: \n',mat_a + mat)
print('\nSubtraction: \n',mat_a - mat)
print('\nMultiplication: \n',mat_a * mat)

Addition: 
 [[10  2  5]
 [12 11  7]
 [ 9 14  6]]

Subtraction: 
 [[-8 -2  1]
 [ 0 -7 -5]
 [ 3  2 -6]]

Multiplication: 
 [[ 9  0  6]
 [36 18  6]
 [18 48  0]]


In [21]:
one_d = np.array([4,5,6,7])
two_d = np.array([[7,8,9,0],[6,2,6,3]])
broad_cast = two_d + one_d

broad_cast #[4,5,6,7] is added by row

array([[11, 13, 15,  7],
       [10,  7, 12, 10]])

In [22]:
clipped = np.clip(two_d,a_max=8,a_min=2)
clipped

array([[7, 8, 8, 2],
       [6, 2, 6, 3]])

In [23]:
np.ceil([1.2, 2.5, 3.8])

array([2., 3., 4.])

In [27]:
new_mat = np.where(mat<5,mat,100)
new_mat

array([[100,   2,   2],
       [100, 100, 100],
       [  3, 100, 100]], dtype=int32)

In [25]:
a = np.array([[3,4],[5,6]])
b = np.array([[2,3],[7,9]])
np.dot(a,b)

array([[34, 45],
       [52, 69]])

In [26]:
# The first array is a one dimensional array
# Second array is a two dimensional array